# -*- coding: utf-8 -*-
"""Model_RF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bZ1B00Z5tQJ8zFEWpnq-A31uFdHO1nQ

# Set Up Model

Install & Import Library
"""

!pip install -q imbalanced-learn

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import joblib
import os
from google.colab import drive

from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

sns.set(style="whitegrid")

"""# Data Selection

Mount Drive & Load CSV
"""

drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/skripsi/Dataset/Data_siswa.csv"

df = pd.read_csv(dataset_path, sep=None, engine='python')

df.columns = df.columns.str.replace('\ufeff', '', regex=False)

print("Ukuran dataset:", df.shape)
display(df.head())
print("Jumlah data setelah load :", df.shape[0])
print("Jumlah kolom             :", df.shape[1])

"""Validasi Dataset"""

required_columns = [
    "Intensitas_Belajar",
    "Fokus_Belajar",
    "Disiplin_Belajar",
    "Interaksi_Belajar",
    "Teknologi",
    "Lingkungan_Belajar",
    "Waktu_Efektif",
    "Gaya_Belajar"
]

missing_cols = [col for col in required_columns if col not in df.columns]

if missing_cols:
    raise ValueError(f"Kolom berikut tidak ditemukan dalam dataset: {missing_cols}")
else:
    print("Semua kolom penting tersedia ✔")

"""Cek struktur dataset"""

feature_cols = [
    "Intensitas_Belajar",
    "Fokus_Belajar",
    "Disiplin_Belajar",
    "Interaksi_Belajar",
    "Teknologi",
    "Lingkungan_Belajar",
    "Waktu_Efektif"
]

target_col = "Gaya_Belajar"

tabel_variabel = pd.DataFrame({
    "No": range(1, len(feature_cols) + 2),
    "Variabel": feature_cols + [target_col],
    "Peran": ["Fitur"] * len(feature_cols) + ["Target"],
    "Tipe Data": ["Kategorikal"] * (len(feature_cols) + 1)
})

print("Tabel Variabel Penelitian:")
display(tabel_variabel)

"""# Data Preparation

Data Cleaning
"""

df_model = df.copy()

print("Jumlah data awal:", df_model.shape)

df_model = df_model.replace(r'^\s*$', np.nan, regex=True)

print("\nMissing value sebelum cleaning:")
print(df_model.isna().sum())

df_model = df_model.drop_duplicates().reset_index(drop=True)
print("\nJumlah baris duplikat: ",df.duplicated().sum())

print("\nJumlah data setelah hapus duplikat:", df_model.shape)

imputer = SimpleImputer(strategy='most_frequent')

df_model[feature_cols] = imputer.fit_transform(df_model[feature_cols])

print("\nMissing value setelah imputasi:")
print(df_model.isna().sum())
print("Jumlah data setelah cleaning :", df_model.shape[0])

"""Drop Atribut Identitas"""

df_model = df_model.drop(
    columns=[
        'ID_Siswa',
        'Sekolah',
        'Nomor_Absen',
        'Nama',
        'Kelamin',
        'Kelas'
    ],
    errors='ignore'
)

print("Kolom setelah menghapus atribut identitas:")
print(df_model.columns.tolist())

"""Seleksi Fitur Model"""

feature_cols = [
    "Intensitas_Belajar",
    "Fokus_Belajar",
    "Disiplin_Belajar",
    "Interaksi_Belajar",
    "Teknologi",
    "Lingkungan_Belajar",
    "Waktu_Efektif"
]

target_col = "Gaya_Belajar"

df_model = df_model[feature_cols + [target_col]]

print("Struktur dataset setelah seleksi fitur:")
display(df_model.head())

"""Encoding Target Label"""

X = df_model[feature_cols].copy()
y_raw = df_model[target_col].astype(str).copy()

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y_raw)

mapping_df = pd.DataFrame({
    "Kelas Gaya Belajar": target_encoder.classes_,
    "Kode Numerik": range(len(target_encoder.classes_))
})

print("Mapping Label Encoding:")
display(mapping_df)

"""Split Data (70:30, Stratified)"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print(" Ringkasan pembagian data 70:30 (stratified):")
display(tabel_split)

"""Analisis Distribusi & Penentuan CV"""

train_dist = pd.Series(target_encoder.inverse_transform(y_train)).value_counts()
test_dist  = pd.Series(target_encoder.inverse_transform(y_test)).value_counts()

tabel_distribusi_train_test = pd.DataFrame({
    "Kelas": sorted(target_encoder.classes_),
    "Train": [int(train_dist.get(k, 0)) for k in sorted(target_encoder.classes_)],
    "Test":  [int(test_dist.get(k, 0)) for k in sorted(target_encoder.classes_)]
})

display(tabel_distribusi_train_test)

class_counts = pd.Series(y_train).value_counts().sort_index()
min_class = int(class_counts.min())
max_class = int(class_counts.max())
ratio = max_class / min_class

print("Distribusi kelas data latih:")
print(class_counts)
print("Rasio ketidakseimbangan:", round(ratio,2))

cv_folds = max(2, min(5, min_class))
cv = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=42)

print("Jumlah fold cross-validation:", cv_folds)

"""Cek Imbalance dan Tentukan CV"""

class_counts = pd.Series(y_train).value_counts().sort_index()
min_class = int(class_counts.min())
max_class = int(class_counts.max())
ratio = (max_class / min_class) if min_class > 0 else 0

print("Distribusi kelas pada data latih:")
print(class_counts)

print(f"\nJumlah data kelas minimum : {min_class}")
print(f"Jumlah data kelas maksimum: {max_class}")
print(f"Rasio ketidakseimbangan   : {ratio:.2f}")

cv_folds = max(2, min(5, min_class))
cv = StratifiedKFold(
    n_splits=cv_folds,
    shuffle=True,
    random_state=42
)

"""# Modeling RF

Pipeline Preprocessing (Imputer + OrdinalEncoder) + RF + Review Transformasi
"""

preprocess_steps = [
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))
]

preprocess_pipeline = Pipeline(steps=preprocess_steps)

preprocess_view = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))
])

X_view = df_model[feature_cols]
X_transformed = preprocess_view.fit_transform(X_view)

df_transformed = pd.DataFrame(X_transformed, columns=feature_cols)

print("Contoh hasil transformasi fitur (5 data):")
display(df_transformed.head())

"""Random Forest Model"""

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

print("Parameter awal Random Forest:")
print(rf)

"""Integrasi ke Pipeline"""

pipeline = ImbPipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)),
    ("rf", rf)
])

print("Pipeline model:")
for name, _ in pipeline.steps:
    print("-", name)

"""Hyperparameter Tuning (StratifiedKFold + RandomizedSearchCV)"""

param_dist = {
    "rf__n_estimators": [100, 150, 200],
    "rf__max_depth": [None, 10, 15, 20],
    "rf__min_samples_split": [2, 3, 5],
    "rf__min_samples_leaf": [1, 2, 4],
    "rf__max_features": ["sqrt", "log2"]
}

search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=30,
    scoring="f1_macro",
    cv=cv,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

print("Proses tuning dimulai...")
search.fit(X_train, y_train)

best_model = search.best_estimator_

param_desc = {
    "rf__n_estimators": "Jumlah pohon keputusan dalam Random Forest",
    "rf__max_depth": "Kedalaman maksimum setiap pohon",
    "rf__min_samples_split": "Minimum jumlah data untuk membentuk percabangan",
    "rf__min_samples_leaf": "Minimum jumlah data pada daun pohon",
    "rf__max_features": "Jumlah fitur yang dipertimbangkan pada setiap percabangan"
}

rows = []
for param, values in param_dist.items():
    rows.append({
        "Parameter": param.replace("rf__", ""),
        "Rentang Nilai yang Diuji": ", ".join([str(v) for v in values]),
        "Keterangan": param_desc.get(param, "-")
    })

tabel_param = pd.DataFrame(rows)

print("Tabel parameter yang dioptimasi:")
display(tabel_param)

"""Hasil Parameter Terbaik"""

print("\nBest Parameters Random Forest:")
for k, v in search.best_params_.items():
    print(f"{k}: {v}")

print(f"\nBest CV F1-macro: {search.best_score_:.4f}")

"""# Evaluasi Model

Prediksi Data Uji
"""

y_pred = best_model.predict(X_test)

print("Jumlah data uji:", len(y_test))

"""Performance Metrics"""

acc = accuracy_score(y_test, y_pred)
f1m = f1_score(y_test, y_pred, average="macro")

print(f"Accuracy : {acc*100:.2f}%")
print(f"F1-score : {f1m:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=target_encoder.classes_,
    digits=4
))

""" Confusion Matriks"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7,6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    linewidths=0.5,
    linecolor='black',
    cbar=True,
    xticklabels=target_encoder.classes_,
    yticklabels=target_encoder.classes_
)

plt.xlabel("Kelas Prediksi")
plt.ylabel("Kelas Aktual")
plt.title("Confusion Matrix Random Forest")
plt.tight_layout()
plt.show()
print("Kelas:", list(target_encoder.classes_))

""" Feature Importance (Tabel + Grafik)"""

importances = best_model.named_steps['rf'].feature_importances_

fi_df = pd.DataFrame({
    "Fitur": X.columns,
    "Nilai Importance": importances
}).sort_values(by="Nilai Importance", ascending=False)


plt.figure(figsize=(8,5))
bars = plt.bar(
    fi_df["Fitur"],
    fi_df["Nilai Importance"]
)

plt.title("Feature Importance Model Random Forest", fontsize=12)
plt.xlabel("Fitur", fontsize=11)
plt.ylabel("Nilai Importance", fontsize=11)
plt.xticks(rotation=30, ha='right')

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.3f}",
        ha='center',
        va='bottom',
        fontsize=9
    )

plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

print("\nFeature Importance Random Forest:")
display(fi_df)

""" Grafik Skor Cross Validation"""

mean_scores = search.cv_results_['mean_test_score']

plt.figure(figsize=(9,5))
plt.plot(
    range(1, len(mean_scores) + 1),
    mean_scores,
    marker='o',
    linestyle='-'
)

plt.xlabel("Iterasi RandomizedSearch", fontsize=11)
plt.ylabel("Mean CV F1-Score", fontsize=11)
plt.title("Performa Cross Validation pada RandomizedSearchCV", fontsize=12)

best_score = search.best_score_
plt.axhline(
    y=best_score,
    linestyle='--',
    linewidth=1,
    label=f"Best CV F1 = {best_score:.3f}"
)

plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

drive.mount('/content/drive')
output_dir = "/content/drive/MyDrive/skripsi/Model"
os.makedirs(output_dir, exist_ok=True)

artifact = {
    "model": best_model,
    "feature_cols": feature_cols,
    "target_encoder": target_encoder,
    "target_classes": target_encoder.classes_
}

model_path = os.path.join(output_dir, "model_rf_gaya_belajar1.joblib")
joblib.dump(artifact, model_path)

print(f"Model berhasil disimpan di: {model_path}")